{% set name = "types-six" %}
{% set version = "1.17.0.20241205" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1f662347a8f3b2bf30517d629d82f591420df29811794b0bf3804e14d716f6e0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/six-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for six
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
